### ISSUE TITLE
Just a general question about performance

### ISSUE THREAD

**Issue by jdgong** [hirohisa/ImageLoaderSwift#37]
Hi 

I am asking a general question regarding performance since I am choosing one image downloader now. How is the performance of ImageLoaderSwift compared with using AFNetworking, SDWebimage, or swift counterpart such as Haneke, KFSwiftImageLoader, etc. Thanks very much!

**Comment by hirohisa** [comment]
I have used AFNetworking and SDWebImage as image loader. SDWebImage has high performance, but it is a huge library and has many options and supports formats. I create this library because I want to more lightweight and hight performance library.

Reference: https://github.com/bpoplauschi/ImageCachingBenchmark
